### ISSUE TITLE
'Market' object has no attribute 'bitshares'

### ISSUE THREAD

**Issue by litepresence** [bitshares/python-bitshares#100]
> litepresence, [04.05.18 12:47]
> any thoughts on what I may have broken?  after creating market object:
> market = Market(
>                 BitPAIR,
>                 bitshares_instance=BitShares(
>                     nodes,
>                     num_retries=0),
>                 mode='head')
> then making this pybitshares call:if market.bitshares.wallet.locked(): is now throwing an odd error I've never seen before: AttributeError ("'Market' object has no attribute 'bitshares'",)
> I'm able to print market and I get the dictionary with two asset ID's.   and I'm able to print market.ticker() and I get the ticker details
> 
> Fabian Schuh, [04.05.18 23:43]
> Can you open an issue on github with a minimum example that shows that error? 

```
from bitshares import BitShares
from bitshares.market import Market
from bitshares.account import Account
from random import shuffle
from getpass import getpass

BitPAIR = 'BTS:OPEN.BTC'

nodes = [
    'wss://relinked.com/ws',
    'wss://dexnode.net/wss',
    'wss://this.uptick.rocks/ws',
    'wss://eu.nodes.bitshares.works/wss']

while 1:
    try:
        USERNAME = input('Account: ')
        account = Account(
            USERNAME,
            bitshares_instance=BitShares(
                nodes,
                num_retries=0))
        market = Market(
            BitPAIR,
            bitshares_instance=BitShares(
                nodes,
                num_retries=0),
            mode='head')
        PASS_PHRASE = getpass(prompt='Pass Phrase: ')
        market.bitshares.wallet.unlock(PASS_PHRASE)
        print('AUTHENTICATED - YOUR WALLET IS UNLOCKED')
        break
    except Exception as e:
        print (type(e).__name__, e.args, 'try again...')
        shuffle(nodes)
        pass

'''
Account: litepresence1
Pass Phrase: 
AttributeError ("'Market' object has no attribute 'bitshares'",) try again...
'''
```

**Comment by xeroc** [comment]
fixed in `develop`
