### ISSUE TITLE
can't open doc site (https misconfig)

### ISSUE THREAD

**Issue by Lavande** [bitshares/python-bitshares#101]
Open https://docs.pybitshares.com/ with Chromium, you'll get this prompt:

> This server could not prove that it is docs.pybitshares.com; its security certificate is from *.readthedocs.io. This may be caused by a misconfiguration or an attacker intercepting your connection.

**Comment by abitmore** [comment]
README says http://docs.pybitshares.com/ (without "s").

**Comment by Lavande** [comment]
oops, sorry, my 'https everywhere' addon added 's' automatically.
BTW, any plan to make it https available? (though trivial)

**Comment by clockworkgr** [comment]
See here https://github.com/rtfd/readthedocs.org/issues/2652
