### ISSUE TITLE
Support channels for this module

### ISSUE THREAD

**Issue by metaperl** [bitshares/python-bitshares#110]
Following up on [deverick's comments](https://github.com/bitshares/python-bitshares/issues/2#issue-220514172):

1. What are the support channels for this module?
2. I do not see the contributing page that deverick speaks of. Where is that contributing page?
3. Could [the opening frontpiece](http://docs.pybitshares.com) be a place to publish the support channels?

**Comment by xeroc** [comment]
> What are the support channels for this module?

We (rather "I") don't have that. What would you propose to get this set up? Telegram group maybe?

> I do not see the contributing page that deverick speaks of. Where is that contributing page?

Doesn't exist either. Recommendations are welcome.

> Could the opening frontpiece be a place to publish the support channels?

It could be put into README as well as on pybitshares.com (which presents the stuff in docs/)

**Comment by metaperl** [comment]
> We (rather "I") don't have that. What would you propose to get this set up? Telegram group maybe?

Hmm, whatever your preference is. Telegram/Discord are both fine with me.

> It could be put into README as well as on pybitshares.com (which presents the stuff in docs/)

Sounds good.

Sorry to vex you during your vacation :)

**Comment by xeroc** [comment]
> Hmm, whatever your preference is. Telegram/Discord are both fine with me.

Here we go: https://t.me/joinchat/AMgHPELjSJ57IGwW8sbgbw

Anyone knows how to get a nicer looking link in telegram?
