### ISSUE TITLE
Getting filled order

### ISSUE THREAD

**Issue by anthon-alindada** [bitshares/python-bitshares#114]
Hi can someone please help me, I've been trying to find a way to know if an order was filled?
So if i use the Market module and try to buy or sell. is there a way of knowing if the order was filled or not?
Also if i use the blokchain stream i dont get any "fill_order" action.
Thank you.

**Comment by xeroc** [comment]
If you have the order id (`1.7.xxx`) and you try to obtain that object, it should return empty.
That is what is happening here: https://github.com/bitshares/python-bitshares/blob/master/bitshares/price.py#L453
