### ISSUE TITLE
there is a bug in dex.py

### ISSUE THREAD

**Issue by jackingyang** [bitshares/python-bitshares#116]
name 'maintenance_col_ratio' is not defined
when debt_positions si 0.
![2018-07-16 4 45 20](https://user-images.githubusercontent.com/6406480/42750151-bff4c874-8918-11e8-97fb-bb5a4074563d.png)

**Comment by jackingyang** [comment]
wait for 3.0?

**Comment by xeroc** [comment]
Sorry for being late on this issue.
The collateral ratio should probably be 0 in case of no debt. I'll look into fixing this.
