### ISSUE TITLE
Assert Exception: now <= trx.expiration

### ISSUE THREAD

**Issue by TreantBG** [bitshares/python-bitshares#122]
Hello i'm getting this error 
bitsharesapi.exceptions.UnhandledRPCError: Assert Exception: now <= trx.expiration:

i haven't change anything to my code.
this is the operation expiration that i found in debug mode "expiration": "2018-08-07T13:16:18"
its well after now.

**Comment by TreantBG** [comment]
i found the problem

in transactionbuilder.py
line 302
```
 expiration = transactions.formatTimeFromNow(
            self.expiration or self.blockchain.expiration
        )
```
formatTimeFromNow expects secs => integer
self.expiration returns string => already formatted earlier with formatTimeFromNow

i will create pull request

**Comment by TreantBG** [comment]
i found the problem
the expiration time is too low in transactionbuilder.py

i replace it with this code and it works now

line 302
```
expiration_time = self.expiration or self.blockchain.expiration
expiration = transactions.formatTimeFromNow(
            expiration_time if expiration_time > 100 else 3000
        )
```

originally expiration_time is 30 and i don't know why it's not working

**Comment by xeroc** [comment]
You can also use

```
bitshares = BitShares(expiration=300)
```
