### ISSUE TITLE
How can I add a new token/coin for trading using pybitshares market module ?

### ISSUE THREAD

**Issue by rajqumar** [bitshares/python-bitshares#125]
@bitfag @Zapata I am working on a decentralised exchange, I want to add any custom token from Ethereum or any other blockchain platform. How can I do this ?

**Comment by xeroc** [comment]
This is the issue tracker of pybitshares and thus focus on python development alone.
For developing a "gateway" which is what you need, you should probably hire someone that can assist with development.
