### ISSUE TITLE
Pybitshares only one account is getting created

### ISSUE THREAD

**Issue by rajqumar** [bitshares/python-bitshares#135]
I am using pybitshares for generating wallet accounts for my users, I hit the bitshares.wallet.create() and want to store the keys to database but this function always returns null and when I check bitshares.wallet.created() it results true.

```
from bitshares import BitShares
bitshares = BitShares()
bitshares.wallet.create("secret-passphrase")
```

getting none on this code

Please help @SmileyChris  @xeroc @elmato @Zapata @calvinfroedge

**Comment by xeroc** [comment]
This should be fixed by the release of pygraphene-1.0.0 and subsequent update of pybitshares (pending)
