### ISSUE TITLE
Failed to compare two Price

### ISSUE THREAD

**Issue by jude90** [bitshares/python-bitshares#14]
```python
>>> bts_cny = Market("BTS:CNY",bitshares_instance=bit)
>>> p2 = bts_cny.ticker()['highestBid']
>>> p3 = bts_cny.ticker()['highestBid']
>>> p2 > p3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/bitshares/price.py", line 314, in __gt__
    assert other["quote"]["symbol"] == self["base"]["symbol"]
AssertionError

```
It doesn't make sense that two price with same base & quote can't compare with each other .
I thought that was a mistake with copy & paste .
the asserts in magic methods of Prince class should be fixed

**Comment by xeroc** [comment]
That assertion is plain wrong    thanks for the report .. Need more tests for those methods in price.py

**Comment by xeroc** [comment]
This still a thing?
