### ISSUE TITLE
Can't update graphenelib

### ISSUE THREAD

**Issue by joelvai** [bitshares/python-bitshares#145]
Why is graphenelib forced to use version 0.6.6 or lower in the python-bitshares requirements. I would need to update this to get rid of deprecation warning caused by graphenelib.

"CryptographyDeprecationWarning: signer and verifier have been deprecated. Please use sign and verify instead."

**Comment by xeroc** [comment]
Sorry about that, but the most recent version of pygraphene brings breaking changes.
I expect the release of a new pybitshares version to happen shortly.

In the meantime, you can always install from the repo's develop branch with something like this:

    pip3 install -e git://github.com/bitshares/python-bitshares@develop#egg=bitshares

**Comment by joelvai** [comment]
Thank you for your response.
