### ISSUE TITLE
Improve BlockchainInstance class usage

### ISSUE THREAD

**Issue by Algruun** [bitshares/python-bitshares#151]
In such classes like ProposalBuilder, TransactionBuilder we can see usage of BlockchainInstance in such way
`BlockchainInstance.__init__(self, **kwargs)`
But it's not pythonic way, there are a lot of warnings - from `Expected type 'BlockchainInstance', got 'TransactionBuilder' instead` to `Unresolved attribute reference 'blockchain' for class 'TransactionBuilder'`.
I suggest inherit from class BlockchainInstance instead of using it in this way.

**Comment by xeroc** [comment]
I am passing `**kwargs` over to the `__init__()` method so that I can extract variables like `blockchain_instance`.
Anyways, I agree that it should inherit from `BlockchainInstance` too.
