### ISSUE TITLE
Message verified with wrong account

### ISSUE THREAD

**Issue by eqld** [bitshares/python-bitshares#156]
Documentation of method `Message.verify()` claims that optional "account" argument gets checked if passed. However, implementation does not take it into account. As a result, invocation of that method with passed value of "account" argument may end up if false positive result.

**Comment by xeroc** [comment]
It does so [here](https://github.com/bitshares/python-bitshares/blob/master/bitshares/message.py#L131-L160)

1. Obtain account and memo key from message
2. validate account exists on chain
3. ensure that provided memo key matches the key to that account on chain
