### ISSUE TITLE
account.refresh() seems like not working as expected

### ISSUE THREAD

**Issue by SERDAR-AKIN** [bitshares/python-bitshares#159]
I am getting "call_orders" information via this commands
but a few hours later it is not getting fresh data from node
from bitshares.account import Account
account = Account("account name", full=True)

#loop start#
account.refresh()
account["call_orders"]
#loop stop#

**Comment by xeroc** [comment]
if `full` is set, the `Account` class will use another API call to obtain data from the backend.
That call returns a key for `call_orders` and hence should be updated everything you run `refresh()`.

you can see it in action with `uptick`:

    uptick -v15 calls <accountname>

**Comment by henryw2019** [comment]
@kuruharbi   try `account.clear_cache()` instead of `account.refresh()`

**Comment by bitProfessor** [comment]
> @kuruharbi try `account.clear_cache()` instead of `account.refresh()`

Seems not working

**Comment by bitProfessor** [comment]
> account.refresh() seems like not working as expected

Has the problem been solved?
