### ISSUE TITLE
Invalid returnOrderId in bitshares/market sell/buy type annotation

### ISSUE THREAD

**Issue by Algruun** [bitshares/python-bitshares#173]
In annotation returnOrderId is string
```
:param string returnOrderId: If set to "head" or "irreversible" the call will wait for the tx to appear in
                                        the head/irreversible block and add the key "orderid" to the tx output
```
But it used only like a bool
```
        if returnOrderId:
            # Make blocking broadcasts
            prevblocking = self.blockchain.blocking
            self.blockchain.blocking = returnOrderId

        tx = self.blockchain.finalizeOp(order, account["name"], "active", **kwargs)

        if returnOrderId:
            tx["orderid"] = tx["operation_results"][0][1]
            self.blockchain.blocking = prevblocking
```

**Comment by xeroc** [comment]
This is a rather hacky details.
Basically, the `blocking` variable is read in `transactionsbuilder.TransactionBuilder.broadcast()` and results in instanciating `blockchain.Blockchain` with the value of `blocking` as `mode`. That results in the `blockchain.BLockchain.blocks()` call to only look for blocks that are either "head" (most recent) or "irreversible".

I am open for suggestions to make those more clear and easier to maintain
