### ISSUE TITLE
wsconnect : Lost connection to node during wsconnect():

### ISSUE THREAD

**Issue by jackingyang** [bitshares/python-bitshares#181]
code:
        nodList=["wss://bts.open.icowallet.net/ws", #鼓鼓节点
	    "wss://bitshares.dacplay.org/ws",
	    "wss://ws.gdex.top",
	    "wss://api.bts.ai"]
	bitShares = BitShares(nodList)

error:

wsconnect : Lost connection to node during wsconnect(): wss://ws.gdex.top (3/-1) Retrying in 4 seconds
96 wsconnect : Lost connection to node during wsconnect(): wss://api.bts.ai (4/-1) Retrying in 6 seconds
96 wsconnect : Lost connection to node during wsconnect(): wss://bts.open.icowallet.net/ws (5/-1)

**Comment by jackingyang** [comment]
When I restarted the program, everything was all right, but there was an error message later.

**Comment by roelandp** [comment]
are you 100% certain those nodes are working and can you connect with them using curl with the same machine?

**Comment by jackingyang** [comment]
> yes i 100% certain those nodes are working

**Comment by jackingyang** [comment]
> are you 100% certain those nodes are working and can you connect with them using curl with the same machine?
> […](#)
> On 12. Feb 2019, at 13:28, jackingyang ***@***.***> wrote: code: nodList=["wss://bts.open.icowallet.net/ws", #鼓鼓节点 "wss://bitshares.dacplay.org/ws", "wss://ws.gdex.top", "wss://api.bts.ai"] bitShares = BitShares(nodList) error: wsconnect : Lost connection to node during wsconnect(): wss://ws.gdex.top (3/-1) Retrying in 4 seconds 96 wsconnect : Lost connection to node during wsconnect(): wss://api.bts.ai (4/-1) Retrying in 6 seconds 96 wsconnect : Lost connection to node during wsconnect(): wss://bts.open.icowallet.net/ws (5/-1) — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

how to solve this  problem ?

**Comment by jackingyang** [comment]
> > are you 100% certain those nodes are working and can you connect with them using curl with the same machine?
> > […](#)
> > On 12. Feb 2019, at 13:28, jackingyang ***@***.***> wrote: code: nodList=["wss://bts.open.icowallet.net/ws", #鼓鼓节点 "wss://bitshares.dacplay.org/ws", "wss://ws.gdex.top", "wss://api.bts.ai"] bitShares = BitShares(nodList) error: wsconnect : Lost connection to node during wsconnect(): wss://ws.gdex.top (3/-1) Retrying in 4 seconds 96 wsconnect : Lost connection to node during wsconnect(): wss://api.bts.ai (4/-1) Retrying in 6 seconds 96 wsconnect : Lost connection to node during wsconnect(): wss://bts.open.icowallet.net/ws (5/-1) — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.
> 
> how to solve this problem ?
thanks i have solve it

**Comment by xeroc** [comment]
This most probably is the API server that isn't accepting your connections
