### ISSUE TITLE
ObjectCache is not being auto-cleaned for unused objects like Block

### ISSUE THREAD

**Issue by bitfag** [bitshares/python-bitshares#215]
Block instance uses caching by default, thus block loaded once leads to accumulated memory usage and memory exhaustion over time.

Simple example:

```python
def foo(b):
    block_id = int(b[0:8], base=16)
    block = Block(block_id)

Notify(on_block=foo)
notify.listen()
```

`block = Block(block_id, use_cache=False)` fixes the problem

**Comment by xeroc** [comment]
Fixed here: https://github.com/xeroc/python-graphenelib/commit/51363100bf7f0b599325a8de329546b27a143e0d

**Comment by xeroc** [comment]
A "garbage" collector is not planned, however, objects should maybe removed when the expire (after 30 seconds). Currently they will sit there even though they are invalid.
