### ISSUE TITLE
Asyncio support

### ISSUE THREAD

**Issue by bitphage** [bitshares/python-bitshares#226]
To make fast cooperative applications, the library needs asyncio support.

Asyncio support requires the following refactoring:

* Use async websocket library https://github.com/aaugustin/websockets to send/receive queries
* Async versions of `grapheneapi/websocket.py` and `grapheneapi/http.py` classes
* Async versions of all library classes / methods which are doing API calls
* Async versions of `bitshares/notify.py` and `bitsharesapi/websocket.py`, currently they are based on callback-based websocket-client, while **websockets** library is coroutine-bases, so async versions would require a heavy refactor

**Comment by xeroc** [comment]
>     * Use async websocket library https://github.com/aaugustin/websockets to send/receive queries

The way the "API" part works distinguishes different implementations depending on the prefix of the URL. `http(s)://` uses another code than `ws(s)://`... I could potentially add `async+ws(s)://` to work with another websocket library and potentially enable async

>     * Async versions of `grapheneapi/websocket.py` and `grapheneapi/http.py` classes

I'd note replace those but add another module for asyncwebsocket. That way, the library stays backwards compatible (which is critical!)

> * Async versions of all library classes / methods which are doing API calls

Need to look into best ways do do this .. ideally, we can come up with a decorator that enables async in case we connect to an endpoint in an async way. Then we can share code

>     * Async versions of `bitshares/notify.py`

yes, this needs working on

**Comment by bitfag** [comment]
> I'd note replace those but add another module for asyncwebsocket. That way, the library stays backwards compatible (which is critical!)

Yes sure, I meant not replacing these, but adding async version **in addition**.

**Comment by xeroc** [comment]
At this point, I got something working like this:

```
import asyncio
from grapheneasync.rpc import Rpc

logging.basicConfig(level=logging.DEBUG)

s = Rpc("wss://node.bitshares.eu")


async def run():
    await s.connect()
    print(await s.get_dynamic_global_properties())
    await asyncio.sleep(5)
    print(await s.get_dynamic_global_properties())


asyncio.run(run())
```

However, it turns out that due to the way *rpc* is used in the existing client, I fear I need to either do a considerable amount of refactoring, or (as you suggested) setup a separate module that does what you need in an async fashion ..

**Comment by xeroc** [comment]
The outcome so far isn't much, but it works basically:
https://github.com/xeroc/python-graphenelib/pull/94

**Comment by bitfag** [comment]
>For me, it would be helpful to know what kind of calls DEXBot requires and currently uses from pybitshares ...

### Here is the list of methods used by dexbot:

BitShares:
self.bitshares.wallet.created
self.bitshares.wallet.create
self.bitshares.wallet.unlock
self.bitshares.cancel
self.bitshares.txbuffer.clear
self.bitshares.txbuffer.is_empty

RPC calls:
self.bitshares.rpc.get_objects
self.bitshares.rpc.get_limit_orders

Market:
self.market.ticker
self.market.orderbook
self.market.buy
self.market.sell

Asset:
Asset.market_fee_percent

Dex:
Dex.returnFees()

Instantiating the following classes:
Account
Asset
Amount
Order

### Notify

Dexbot also uses bitshares.Notify subsytem to subscribe to the events. As I wrote above, it requires heavy refactor.

**Comment by thehapax** [comment]
> > ```
> > * Use async websocket library https://github.com/aaugustin/websockets to send/receive queries
> > ```

@xeroc 
The websocket-client library https://github.com/websocket-client/websocket-client is actually faster to establish a connection and lighter than the aagustin library. for the aaugustin library it provides server support but if we are only using the client, the client library is enough.  It is also about 0.3 sec faster to make a connection.

**Comment by bitfag** [comment]
websocket-client doesn't have asyncio support.

**Comment by thehapax** [comment]
> websocket-client doesn't have asyncio support.

its not natively built in but you can certainly make it work with asyncio

**Comment by bitfag** [comment]
If you wrap your synchronous code into asyncio coroutine it's still synchronous. This `ws.send(query)` call inside `async_processing()` is **blocking**, while it should not.

**Comment by thehapax** [comment]
ok i see.  it does mean though we can turn synchronous websocket code into asyncio, correct?

**Comment by bitfag** [comment]
What do you mean exactly? If you speaking about example in async-wt-ticker.py, such wrapping doesn't make sense because no switching will occur on IO-bounded calls (`ws.send()`), so no performance gains.

**Comment by thehapax** [comment]
ok i see, never mind.

**Comment by bitfag** [comment]
I started to work on asyncio support here https://github.com/bitfag/python-graphenelib/tree/feature/asyncio

It appears code doubling is inevitable, though lots of `bitshares.BitShares` methods can be refactored to optionally return ops, like this:

```python
    def transfer(return_op=False):
        if return_op:
            return op
        return self.finalizeOp(op, account, "active", **kwargs)

    async def transfer():
        op = super().transfer(return_op=True)
        return await self.finalizeOp(op, account, "active", **kwargs)
```

**Comment by xeroc** [comment]
As a remark, it would be much easier to customize `finalizeOp` and add a return_op parameter there as all methods in bitshares.BitShares() use finalizeOp with `**kwargs`.
Hence, only do that if condition once, not in every method!
