### ISSUE TITLE
Possible error in documentation(or even code) in Notify

### ISSUE THREAD

**Issue by andrewshkovskii** [bitshares/python-bitshares#231]
In [here](https://github.com/bitshares/python-bitshares/blob/master/bitshares/market.py#L36) it says that markets assets notation is <QUOTE>/<BASE>.

When we create Notify instance:
1. `markets` can only be an list of strings, but in docs it says that it could be an Market instance. https://github.com/bitshares/python-bitshares/blob/master/bitshares/notify.py#L21
2. Notation of markets assets is reversed to <BASE>/<QUOTE> in Notify:
https://github.com/bitshares/python-bitshares/blob/master/bitshares/notify.py#L105
It this correct? It is very confusing for me.

**Comment by andrewshkovskii** [comment]
The second issue that i have found:
Let's say that we are using market `BRIDGE.MIDAS/BRIDGE.BTC`, so this is `<QUOTE>/<BASE>` notation.
We create Nofity client for this market - `BRIDGE.MIDAS/BRIDGE.BTC`, subscribe to market events using the same notation `<QUOTE>/<BASE>`

Ok, next- we next step we will do is to take two wallets and make a deal within them.
First wallet will be selling, second wallet will be buying for same price, same amount. 
So - there is seller and buyer wallets and these 'wallets' use same market instance - `BRIDGE.MIDAS/BRIDGE.BTC` to execute buy and sell commands.

When seller open order for sale using `market.sale` there will be an event, like this:

```
event.order_id: 1.7.343246117 
event.market quote/base: BRIDGE.BTC BRIDGE.MIDAS 
event.quote:  BRIDGE.BTC BRIDGE.BTC 
event.for_sale symbol amount:  BRIDGE.MIDAS 0.00086032 
event.sell_price quote amount / base amount:  BRIDGE.BTC 11 / BRIDGE.MIDAS 86032 
```
So we have a sell event.
But there is **no buy open order** event. **BUT** There is both events for order fill - for seller and buyer.

Is that suppose to be like that?

**Comment by xeroc** [comment]
Markets in pybitshares are declared as

`QUOTE:BASE` (where quote is the main asset that you would sell/buy with `.sell()` and `.buy()`)

The graphenebackend sends out two notifications for every filled trade. That's nothing I can prevent in that library - it could at most fiolter it.
