### ISSUE TITLE
Add high-level method for get_limit_orders() RPC call

### ISSUE THREAD

**Issue by bitfag** [bitshares/python-bitshares#244]
There is a RPC call to obtain raw orders on the specific market. The difference from `Market.orderbook` is that orderbook() methods does order consolidation and hides all the details. Instead, `get_limit_orders()` show whole details.

`self.bitshares.rpc.get_limit_orders(asset_id_a, asset_id_b, depth)`

Would be nice to have a high-level wrapper method for this maybe in Market class

```python
m = Market('BTS/USD')
depth = 100
m.get_limit_orders(depth)
```

**Comment by xeroc** [comment]
Please see of this does what you are looking for

**Comment by bitfag** [comment]
Looks good, thanks!
