### ISSUE TITLE
account open order rate doesn't go below 0

### ISSUE THREAD

**Issue by grctest** [bitshares/python-bitshares#25]
Hey,

I've been working on a HUG REST API using this library, and found the following when using account 'openorder':

```12,500 WHALESHARE 500 BEYONDBIT @ 0 BEYONDBIT/WHALESHARE```

It should be showing 0.04 BEYONDBIT/WHALESHARE, but it's showing 0?

Cheers 👍

**Comment by xeroc** [comment]
That's an interesting behavior ... basically .. I don't yet know how to get the actual precision for a price when two assets with different precision are involved. I'll look into it.
Either way, the actual variable should hold more accurate information, only the `__str__()` version of it may be rigged
