### ISSUE TITLE
Support BSIP81 Maker Taker

### ISSUE THREAD

**Issue by winston-1984** [bitshares/python-bitshares#282]
**Is your feature request related to a problem? Please describe.**

post BSIP81 Maker Fees are the old Market Fees and a new fee "Taker" is charged.
pybitshares does not support the Taker

this effects both viewing the market taker fee as the trader
and creating/updating the market taker fee as the asset issuer 

**Describe the solution you'd like**

test to ensure compatibility with the new feature, make changes to the library and documentation as needed to support

**Additional context**
keywords "market_fee_percent" , "marketFeePercent

**Comment by xeroc** [comment]
I don't follow what you are requesting.
