### ISSUE TITLE
503 Service Unavailable

### ISSUE THREAD

**Issue by page1** [bitshares/python-bitshares#298]
Hi BitShares community!
I've had an application reading wallet data for my account for a few years now that died **21 days ago (Sept 28 ~4-6am UTC)**.

Now I'm getting 503 errors with retry limits being hit:
    `Handshake status 503 Service Unavailable`
    `grapheneapi.exceptions.NumRetriesReached`

My code is blowing up on code that's very similar to the tutorial: 
```
from bitshares.account import Account
account = Account("init0")
```

I've updated with `pip install --upgrade git+https://github.com/bitshares/python-bitshares.git` showing `Successfully installed bitshares-0.7.0`

Anyone know what changed (my code was the same through this period, so something somewhere else changed)? Any updates I need? 
Thanks

**Comment by abitmore** [comment]
IIRC the default API node is offline. Please try another node.

E.G.
```
b = BitShares()
b.connect(node="wss://api.dex.trading/")

set_shared_bitshares_instance(b)

...
```

 Currently available nodes:

```
wss://dex.iobanker.com/ws
wss://ws.gdex.top
wss://api.weaccount.cn
wss://blockzms.xyz/ws
wss://api.bts.mobi/ws
wss://btsws.roelandp.nl/ws
wss://api.btsgo.net/ws
wss://bts.open.icowallet.net/ws
wss://freedom.bts123.cc:15138/
wss://bitshares.bts123.cc:15138/
wss://bts-seoul.clockwork.gr
wss://api.61bts.com
wss://btsfullnode.bangzi.info/ws
wss://api.dex.trading/
wss://api-bts.liondani.com/ws
wss://public.xbts.io/ws
wss://cloud.xbts.io/ws
wss://node.xbts.io/ws
wss://api.gbacenter.org/ws
wss://api.cnvote.vip:888/
wss://fujian.cnvote.vip:81/
wss://tokyo.bitshares.im/ws
wss://singapore.bitshares.im/ws
wss://bangalore.bitshares.im/ws
wss://newyork.bitshares.im/ws
```

**Comment by abitmore** [comment]
Or
```
from bitshares import BitShares
bts = BitShares("wss://ws.gdex.top")
bts.config.config_defaults['node']='wss://ws.gdex.top'
```

**Comment by page1** [comment]
Thanks @abitmore 
Got it working, too bad the default node list only includes 1 node. 

```
from bitshares import BitShares
from bitshares.account import Account as bts_account

bts = BitShares(node="wss://ws.gdex.top")
return bts_account(account_details['pub_key'], blockchain_instance=bts)
```
