### ISSUE TITLE
What datetime format is needed for market.trade() ?

### ISSUE THREAD

**Issue by grctest** [bitshares/python-bitshares#30]
I'm trying to get market trade history using python-bitshares, and am using the following datetime format:

"2017-12-29T19:16:36Z"

It results in the following error:

"grapheneapi.graphenewsrpc.RPCError: Day of month value is out of range 1..31: Day of month value is out of range 1..31: unable to convert ISO-formatted string to fc::time_point_sec"

Am I not using the proper date format?

More details:
```
Traceback (most recent call last):
  File "/home/btsapi/python-bitshares/bitsharesapi/bitsharesnoderpc.py", line 42, in rpcexec
    return super(BitSharesNodeRPC, self).rpcexec(payload)
  File "/home/btsapi/.local/lib/python3.6/site-packages/grapheneapi/graphenewsrpc.py", line 160, in rpcexec
    raise RPCError(ret['error']['message'])
grapheneapi.graphenewsrpc.RPCError: Day of month value is out of range 1..31: Day of month value is out of range 1..31: unable to convert ISO-formatted string to fc::time_point_sec

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 74, in <module>
    temp_market_history = list(target_market.trades(start="2017-12-20T20:02:08+00:00", stop="2017-12-21T20:02:08+00:00", limit=100))
  File "/home/btsapi/python-bitshares/bitshares/market.py", line 269, in trades
    limit)
  File "/home/btsapi/.local/lib/python3.6/site-packages/grapheneapi/graphenewsrpc.py", line 195, in method
    r = self.rpcexec(query)
  File "/home/btsapi/python-bitshares/bitsharesapi/bitsharesnoderpc.py", line 50, in rpcexec
    raise exceptions.UnhandledRPCError(msg)
bitsharesapi.exceptions.UnhandledRPCError: Day of month value is out of range 1..31: Day of month value is out of range 1..31: unable to convert ISO-formatted string to fc::time_point_sec

```

**Comment by vanissoft** [comment]
I make use of datetime.isoformat() to get a string like '2017-11-30T11:35:27.638665+00:00'

**Comment by xeroc** [comment]
This is the internal format used by bitshares-core:

    timeFormat = '%Y-%m-%dT%H:%M:%S'

you may want to take a look at utils.py, some methods may be of help to you

**Comment by litepresence** [comment]
I'm getting this same error and I have used the methods described above

code and output:

https://pastebin.com/43AhbVaS

**Comment by xeroc** [comment]
`market.trades` expects an instance of `datetime`. Please use

    datetime.utcfromtimestamp(z0)

instead of 

    datetime.utcfromtimestamp(z0).strftime('%Y-%m-%dT%H:%M:%S')
