### ISSUE TITLE
Can't set max_market_fee to 0 in create_asset

### ISSUE THREAD

**Issue by christophersanborn** [bitshares/python-bitshares#303]
In BitShares().create_asset(), at https://github.com/bitshares/python-bitshares/blob/baf7f1ef7e2054356850cbe293498866de3de4d7/bitshares/bitshares.py#L1300 

```
if not max_market_fee:
    max_market_fee = max_supply
```

Should probably be:

```
if max_market_fee is None:
    max_market_fee = max_supply
```

Because if I pass in max_market_fee=0, the existing conditional evaluates true and overrides my explicit zero.

**Comment by xeroc** [comment]
Feel free to make a pull request :D
