### ISSUE TITLE
certificate verify failed: certificate has expired

### ISSUE THREAD

**Issue by lebinbit** [bitshares/python-bitshares#304]
python 3.8.11
`bts = BitShares(node='wss://testnet.xbts.io/ws')` 
It reported an error。

> certificate verify failed: certificate has expired

python 3.6.6
`bts = BitShares(node='wss://testnet.xbts.io/ws')` 
It works.

**Comment by technologiespro** [comment]
one of the solutions is to put a flag in the useragent rejectUnauthorized: false
now all certs is updated

**Comment by lebinbit** [comment]
If I use other nodes, for example，wss://ws.gdex.top.
python 3.8 can be used normally.It seems to be related to the '/ws' path.I think python-bitshares are not very compatible with python3.8 +

**Comment by xeroc** [comment]
unrelated to python library. closing
