### ISSUE TITLE
Memo: decode_memo function

### ISSUE THREAD

**Issue by hjm0520** [bitshares/python-bitshares#32]
Hi @xeroc,

I have an issue regarding the decode_memo function most of the time this works but there are instances that the return of the decode_memo function is ValueError, I understand that the message cannot be decoded as a valid UTF-8 string but the thing is that when I looked at the wallet.bitshares.org the memo is readable I am just wondering why this happens on the decode_memo.

Is there any other way to get fixed the issue? please see the example error below:
ValueError : b'r\x16\xd4\xd3\xd3\xaa(/\x04\xf0\xfa\xc0\xaah\xe7*#\x02\x1aN\x93q\x0e\xc8\x87\xb2v\xf2'

Or am I missing something here?

Thanks in advance

Happy New Year!!!

Henry

**Comment by Podufaly** [comment]
hi. did you fix this problem?
