### ISSUE TITLE
Fetching data on front-end

### ISSUE THREAD

**Issue by qualwebs** [bitshares/python-bitshares#327]
I want to integrate the front-end with the blockchain and also fetch the data stored using `account_storage_map`. Can anyone assist? 
I couldn't find the exact documentation to do so.

**Comment by abitmore** [comment]
As I replied in https://github.com/orgs/bitshares/discussions/2804#discussioncomment-8186105, there is one API that you can use, which is `custom_operations_api::get_storage_info`, and it is described in https://github.com/bitshares/bitshares-core/pull/2620 and https://github.com/bitshares/bitshares-core/pull/1926.

Other documentation(s):
* https://bitshares.github.io/doxygen/classgraphene_1_1app_1_1custom__operations__api.html

For examples, you can take a look at https://t.me/BitSharesDEV/4490 and following messages.

How you would use or show the data on front end is totally up to you.

**Comment by qualwebs** [comment]
Thanks, will explore these options if it fits my needs but hey, what I am not able to wrap my head around, is how do I link the api with the front end ?
Like If I build the front end with react then there aren't any node packages that I can import, there's no mention of this in the documentation either. Will do some research and ask again if required.

**Comment by abitmore** [comment]
@qualwebs you can also check links here: https://github.com/bitshares/awesome-bitshares?tab=readme-ov-file#javascript-libraries
