### ISSUE TITLE
Api error on Market.orderbook

### ISSUE THREAD

**Issue by SERDAR-AKIN** [bitshares/python-bitshares#4]
https://bitshares.org/wallet/#/market/BTS_KAPITAL
![image](https://cloud.githubusercontent.com/assets/26321769/25582036/c804fdbc-2e93-11e7-86a2-33924dc7745d.png)
If you look at the orderbook on the SELL side our first line is 171,875 BTS sell for 11,000 KAPITAL @0,064 KAPITAL/BTS

But when execute this code from API :
from bitshares.market import Market
Market("BTS:KAPITAL").orderbook(limit=1)["asks"]

Output is like that
![image](https://cloud.githubusercontent.com/assets/26321769/25582206/a689d580-2e94-11e7-90de-1611d175ec6e.png)

There is something wrong there...
Please take a look

**Comment by xeroc** [comment]
wow .. that's weird ..
digging into it

**Comment by kuruharbi** [comment]
I am trying to build my own tradebot but some orderbook data comes like that , so that I cant trust API response :(

**Comment by kuruharbi** [comment]
Here is another example for you
https://bitshares.org/wallet/#/market/BTCPLUS_BTS
![image](https://cloud.githubusercontent.com/assets/26321769/26044156/4c571f3e-394b-11e7-9d30-d0ba50d014b3.png)

`from bitshares.market import Market`
`Market("BTCPLUS:BTS").orderbook(limit=1)["asks"]`

![image](https://cloud.githubusercontent.com/assets/26321769/26044202/8b76df74-394b-11e7-82f0-c8ad5d913f4d.png)

**Comment by xeroc** [comment]
That's interesting ... what API node are you using?

**Comment by kuruharbi** [comment]
All examples comes from wss://node.bitshares.eu

**Comment by xeroc** [comment]
This still an issue?
