### ISSUE TITLE
Signed_Transaction usage for Testnet not straightforward

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/python-bitshares#45]
When signing a transaction to be published on the Testnet that contains transfers (in this case exactly one) with memo one needs to do the following:

`transaction = build_your_transaction_with_one_transfer()`
`transaction["operations"][0][1].update({"prefix": "TEST"})`
`tx = Signed_Transaction(**transaction)`
`stx = tx.sign(wifs, chain="TEST").json()`

Not sure if this could be optimized for easy use. Right now I need to know the internal structure of the transaction to update the prefix.

**Comment by xeroc** [comment]
Memo needs to be build explicitly for TESTNET since it contains the chain specific prefix.
It's shown in the unittests `test_transactions.py`
