### ISSUE TITLE
Sign memo with varying keys

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/python-bitshares#47]
With an offline signing service, a feature in the bitshares object to dynamically add and remove wifs from in ram storage would be convenient!

**Comment by xeroc** [comment]
```
bitshares = BitShares(keys=["list of keys"])
# or
bitshares = BitShares(keys={"active":"5asfasasfasfa"})
```

Both are meant for exactly that case

**Comment by sschiessl-bcp** [comment]
That will also establish a new connection, correct?

The idea was to switch keys within the same connection.
