### ISSUE TITLE
The operations has not been added after 10 blocks

### ISSUE THREAD

**Issue by abitmore** [bitshares/python-bitshares#60]
It's reported that, when checking if a transaction is included in a block, the lib compares the full transaction json with result of `get_block` API. But there are issues when producing the json, e.g. converting big numbers from/to json, so sometimes even if a transaction is included in a block, the lib still reports "The operations has not been added after 10 blocks". The correct way is to compare transaction_id's.

Not sure if it's still an issue.

**Comment by xeroc** [comment]
I actually compare the signature because we don't have malleability, and the signature is always a string.
The problem might come from another source .. I'll look into it
