### ISSUE TITLE
Retrieve gateway service info via python-bitshares?

### ISSUE THREAD

**Issue by grctest** [bitshares/python-bitshares#66]
Hey,

Is it possible to retrieve gateway service information from the Bitshares network through python-bitshares, or are they manually configured/implemented in the bitshares-ui?

Cheers 👍

**Comment by xeroc** [comment]
Gateways are manually built into the BitShares-UI wallet and not part of pybitshares.
They also shouldn't be part of the library as they are 3rd party services.
