### ISSUE TITLE
Wallet getPrivateKeyForPublicKey

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/python-bitshares#71]
If the public key is unkown, but only one key is in Wallet.keys, it is still returned.

Is there a use case for this feature? It should be removed for security purposes

**Comment by xeroc** [comment]
The "one" key that is returned comes from `Wallet.keys` and is meant to allow "overwriting" of keys to use for signing such as:

```
bts = BitShares(keys={"active": "5sfafasfassafssaf"})
bts.transfer(...)
```

This will sign with the provided key, no matter what's in the local wallet.

**Comment by sschiessl-bcp** [comment]
Yes, that is what I thought. 

The issue is not to allow overwriting of keys with the constructor, but that any public key returns the private key from the constructor.

I think if one attempts to retrieve a key the proper public key should be passed to the method, otherwise consistency of the module is not ensured.
