### ISSUE TITLE
Creating user

### ISSUE THREAD

**Issue by KolosDan** [bitshares/python-bitshares#83]
Hello. Need help with one function.
bitshares.bitshares.create_account

I am giving account_name, registrar(private keys added to wallet db), referrer and password
Should be enough I though, but exceptions pops out: PrivateKey object is not iterable
What can I do with it?

**Comment by xeroc** [comment]
Can you give a full example call, please?

**Comment by xeroc** [comment]
Fixed .. will be part of next release
