### ISSUE TITLE
Incorrect amount of an unfilled order from account.openorder

### ISSUE THREAD

**Issue by TuJuXorX** [bitshares/python-bitshares#85]
The account.openorder gives only original order amount of an buy or sell order. The current value for partially filled order cannot be obtained at all. This is how I'm trying to get the amount for example for the first order in the list obtained from account.openorders:

```python
from bitshares.account import Account

account = Account("accountname")
print(account.openorders[0]['base']['amount'])
```

This is also the case for market.accountopenorders(). It would be nice to have both original and current amount of an order available.

**Comment by xeroc** [comment]
fixed ... will be in next release
