### ISSUE TITLE
orderbook - got multiple values for keyword argument 'blockchain_instance'

### ISSUE THREAD

**Issue by SaetreS** [bitshares/python-bitshares#94]
It's not possible to get the order book from the Market class.

Error message:

    lib\site-packages\bitshares\price.py", line 484, in __init__
    super(Order, self).__init__(*args, blockchain_instance=self.blockchain, **kwargs)

    TypeError: __init__() got multiple values for keyword argument ``'blockchain_instance'

Code:

    from bitshares.market import Market
    market = Market('USD:BTS')
    print(market.orderbook())

**Comment by SaetreS** [comment]
I don't quite understand the blockchain_instance=self.blockchain calls. By simple returning the orders and ignoring the asks, bids maping that is done and just do that myself it seems that everything works fine.

current code

        asks = list(map(lambda x: Order(
            float(x["price"]),
            quote=Amount(x["quote"], self["quote"], blockchain_instance=self.blockchain),
            base=Amount(x["base"], self["base"], blockchain_instance=self.blockchain),
            blockchain_instance=self.blockchain
        ), orders["asks"]))
        bids = list(map(lambda x: Order(
            float(x["price"]),
            quote=Amount(x["quote"], self["quote"], blockchain_instance=self.blockchain),
            base=Amount(x["base"], self["base"], blockchain_instance=self.blockchain),
            blockchain_instance=self.blockchain
        ), orders["bids"]))

alternative code if pandas would be allowed:

   asks = pd.DataFrame(orders['asks'].astype('float64')
   bids = pd.DataFrame(orders['bids'].astype('float64')
   data = {'asks': asks, 'bids': bids}

**Comment by cballantyne** [comment]
I have hit this as well. It does work on my local machine (Ubuntu 16.04 with python 3.5.2) but bombs out in the same way as above when trying to run in docker container. It doesn't matter what the version of python I use in the docker container (3.5.2, 3.5.5 or 3.6.5).

**Comment by cballantyne** [comment]
I got it working by reverting to release 0.1.13.
